export { default as CopyIcon } from './copy';
export { default as FileIcon } from './file';
export { default as GithubIcon } from './github';
export { default as LinkedinIcon } from './linkedin';
export { default as MailIcon } from './mail';
export { default as MenuIcon } from './menu';
export { default as MoonIcon } from './moon';
export { default as profileImg } from './profile-img.jpg';
export { default as SunIcon } from './sun';
